server:
  port: 8080

---

spring:
  profiles: default
  jpa:
    show_sql: true
      #format_sql: true
    generate-ddl: true
    hibernate:
        ddl-auto: create-drop
  datasource:
    url: jdbc:mariadb://localhost:3306/HairshopReservation
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mihn0621

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: mypage
          destination: hairshop.reservation
          contentType: application/json
        event-out:
          destination: hairshop.reservation
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8084
---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: mypage
          destination: hairshop.reservation
          contentType: application/json
        event-out:
          destination: hairshop.reservation
          contentType: application/json